name: Deploy Serverless Backend

on:
  push:
    branches: [main]

jobs:
  aws-lambda:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Backend/marketplace_server

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ python3-dev

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          pip install pybind11 setuptools

      - name: Build pybind11 extension
        run: |
          python3 setupValidator.py build_ext --inplace
          # Move the built .so to the marketplace_server directory (if not already there)
          find . -name "json_validator*.so" -exec mv {} . \;
            - name: Zip Lambda Function
              run: zip -r function.zip .

      - name: Deploy to AWS Lambda
        uses: aws-actions/aws-lambda-deploy@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          function-name: your-lambda-function-name
          zip-file: function.zip

  gcp-functions:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Backend/marketplace_server

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ python3-dev

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          pip install pybind11 setuptools

      - name: Build pybind11 extension
        run: |
          cd ../
          python3 setupValidator.py build_ext --inplace
          find . -name "json_validator*.so" -exec mv {} marketplace_server/ \;

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: your-gcp-project-id

      - name: Deploy to Google Cloud Functions
        run: |
          gcloud functions deploy your-function-name \
            --runtime python310 \
            --trigger-http \
            --entry-point main \
            --source .