name: Trigger Hottest Daily Admin Function

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 6 * * *'  # TODO Uncomment to run every day at midnight Central Time (UTC-6)

jobs:
  trigger-hottest-daily:
    runs-on: ubuntu-latest
    steps:
      - name: Call hottest daily admin endpoint (fire-and-forget)
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.ADMIN_SERVICE_TOKEN }}" \
            -H "Content-Type: application/json" \
            --max-time 10 \
            --data '{}' \
            --output /dev/null \
            --silent \
            --show-error \
            --fail \
            https://your-api-url.example.com/admin/hottest-daily || true
        # The '|| true' ensures the workflow does not fail if the endpoint is slow or returns an error
